### **Overview**
RandomizedSearchCV is a hyperparameter tuning technique in scikit-learn that allows you to search over a specified parameter distribution. Unlike GridSearchCV, which evaluates all possible combinations of parameters, RandomizedSearchCV randomly samples a fixed number of parameter settings from the specified distributions, making it more efficient for large parameter spaces or when computational resources are limited.

### **Key Features**
> Efficiency:
Evaluates a fixed number of parameter combinations, making it computationally cheaper than GridSearchCV.

> Random Sampling:
Allows sampling from continuous distributions for hyperparameters.

> Cross-Validation:Automatically performs cross-validation to validate each combination of parameters.

> Scoring Metrics: Supports various scoring metrics to optimize model performance.

> Parallel Processing: Can utilize multiple CPU cores for faster execution.

### When to Use RandomizedSearchCV
>
When the parameter space is large or contains continuous distributions.
When you want to balance computational cost with the likelihood of finding good hyperparameter values.
When approximate solutions are sufficient, and exhaustive search is infeasible

# Import Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

In [3]:
df = pd.read_csv('/content/sample_data/diabetes.csv')

df.head().style.set_properties(**{'background-color' : 'white',
                           'color' : 'Blue',
                           'border-color' : 'Blue',
                           'font-size':'15px','font-family' :'Times Roman New'})

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [14]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [16]:
df.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

# split the dataset

In [6]:
X = df.drop(['Outcome'],axis=1)
y = df['Outcome']

In [7]:
X.head(3)

   Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0            6      148             72  ...  33.6                     0.627   50
1            1       85             66  ...  26.6                     0.351   31
2            8      183             64  ...  23.3                     0.672   32

[3 rows x 8 columns]

In [8]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [44]:
X_train,X_test,y_train,y_test = train_test_split(

                                                 X,y,
                                                 test_size= 0.2,
                                                 random_state= 42
)

In [45]:
X_train.head(2)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
60             2       84              0  ...   0.0                     0.304   21
618            9      112             82  ...  28.2                     1.282   50

[2 rows x 8 columns]

In [46]:
X_train.shape,y_train.shape

((614, 8), (614,))

# Develop the model

> This is a defualt model , all parameter and performance are cuased by only the model deafults working.

In [47]:
model = RandomForestClassifier(n_estimators=100)

model.fit(X_train,y_train)

RandomForestClassifier()

> model is trained with train X,y.

## check deafult model score & defualt model params

In [48]:
accuracy = model.score(X_test,y_test)
accuracy

0.7207792207792207

In [49]:
accuracy = round(model.score(X_test,y_test) *100 ,2  )
accuracy

72.08

## see the defualt params

In [50]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

# Hyperparameter Tuning

In [71]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

params = {
    'n_estimators' : randint(30,300),
    'max_depth' : [None,5,10,15,20,30,35],
    'max_features': ['sqrt','log2',None],
    'min_samples_split': randint(2,11),
    'min_samples_leaf' : randint(1,10),
    'bootstrap'        :[True,False],
    'criterion'        :['gini','entropy']
}

# apply randomized Search CV

In [78]:
model = RandomForestClassifier()


RandomSearch = RandomizedSearchCV(
    estimator = model,
    param_distributions= params,
    n_iter = 10,
    scoring = 'accuracy',
    n_jobs = -1,
    random_state= 42,
    cv = 5,
    verbose = 0,

)

RandomSearch.fit(X_train, y_train) # Fit with train data.

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'criterion': ['gini', 'entropy'],
                                        'max_depth': [None, 5, 10, 15, 20, 30,
                                                      35],
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x79446acd17c0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x79446acd0cb0>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x79446aee0830>},
                   random_state=42, scoring='accuracy')

### accuracy comparison

In [79]:
accuracy_after_hypertuning = round(RandomSearch.score(X_test,y_test) *100,2)
accuracy_after_hypertuning

74.68

## check best params

In [80]:
RandomSearch.best_params_

{'bootstrap': False,
 'criterion': 'entropy',
 'max_depth': 10,
 'max_features': 'log2',
 'min_samples_leaf': 5,
 'min_samples_split': 3,
 'n_estimators': 221}

In [81]:
y_predict = RandomSearch.predict(X_test)
y_predict

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])