# Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/sample_data/play_tennis.csv')
df.head(10)

   day   outlook  temp humidity    wind play
0   D1     Sunny   Hot     High    Weak   No
1   D2     Sunny   Hot     High  Strong   No
2   D3  Overcast   Hot     High    Weak  Yes
3   D4      Rain  Mild     High    Weak  Yes
4   D5      Rain  Cool   Normal    Weak  Yes
5   D6      Rain  Cool   Normal  Strong   No
6   D7  Overcast  Cool   Normal  Strong  Yes
7   D8     Sunny  Mild     High    Weak   No
8   D9     Sunny  Cool   Normal    Weak  Yes
9  D10      Rain  Mild   Normal    Weak  Yes

# seperate target column

In [3]:
X = df.drop(columns=['day','play'])
y = df['play']

In [4]:
X

     outlook  temp humidity    wind
0      Sunny   Hot     High    Weak
1      Sunny   Hot     High  Strong
2   Overcast   Hot     High    Weak
3       Rain  Mild     High    Weak
4       Rain  Cool   Normal    Weak
5       Rain  Cool   Normal  Strong
6   Overcast  Cool   Normal  Strong
7      Sunny  Mild     High    Weak
8      Sunny  Cool   Normal    Weak
9       Rain  Mild   Normal    Weak
10     Sunny  Mild   Normal  Strong
11  Overcast  Mild     High  Strong
12  Overcast   Hot   Normal    Weak
13      Rain  Mild     High  Strong

In [5]:
y

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: play, dtype: object

In [6]:
y.value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

# Encode the categorical

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [9]:
X_encoded =X.copy()

for col in X_encoded.columns :
  X_encoded[col] = le.fit_transform(X_encoded[col])

X_encoded

    outlook  temp  humidity  wind
0         2     1         0     1
1         2     1         0     0
2         0     1         0     1
3         1     2         0     1
4         1     0         1     1
5         1     0         1     0
6         0     0         1     0
7         2     2         0     1
8         2     0         1     1
9         1     2         1     1
10        2     2         1     0
11        0     2         0     0
12        0     1         1     1
13        1     2         0     0

In [14]:
y_encoded = LabelEncoder().fit_transform(y)

y_encoded.shape

(14,)

# Split the datasets

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(

                                                 X_encoded,
                                                 y_encoded,
                                                 test_size= 0.2,
                                                 random_state= 42
)

# Train Model

In [16]:
from sklearn.naive_bayes import CategoricalNB

model = CategoricalNB()

model.fit(X_train,y_train)

CategoricalNB()

# predict

In [17]:
y_pred = model.predict(X_test)

print(y_pred)

[1 0 1]

In [18]:
print(y_test)

[1 1 0]

# evaluation

In [19]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.3333333333333333