# Load the datasets

In [115]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [116]:
df = pd.read_csv('/content/sample_data/finnova_train.csv')
df.head(50)

,Txn_ID,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,...,Feature_21,Feature_22,Feature_23,Feature_24,Feature_25,Feature_26,Feature_27,Feature_28,Txn_Value,Risk_Flag
0,TXN173209,-2.183585,1.892761,-1.142737,-2.436105,1.396925,3.717930,-2.123038,-1.543484,-0.481181,...,-0.564747,-0.400373,0.350173,0.993206,-0.139172,0.736772,0.113477,0.148835,0.61,0.0
1,TXN159667,-1.546892,1.850485,2.176940,3.035659,-1.192864,0.955754,-1.758738,-1.797986,-0.829465,...,-1.286355,0.351282,0.008838,0.320438,-0.074777,0.232331,0.071991,0.134451,0.00,0.0
2,TXN157896,-1.522655,1.081601,0.182110,0.990186,1.586729,4.474267,-0.949357,1.709973,-0.447918,...,-0.012369,-0.211502,0.074203,0.986499,0.014727,-0.134744,-0.839414,-0.318542,37.05,0.0
3,TXN103239,-0.664094,0.425969,2.691272,-1.700911,-0.376081,-0.673883,0.437586,-0.247356,2.562786,...,-0.150361,0.098032,-0.369068,0.336507,0.471566,-0.840827,-0.092741,-0.154443,14.53,0.0
4,TXN111043,-0.618800,0.601447,1.676447,-0.858323,-0.204625,-0.458810,0.958814,-0.406579,-1.380236,...,-0.397481,-0.593460,0.038502,0.321442,-0.458293,-0.860966,-0.238523,-0.083199,65.27,0.0
5,TXN162223,1.162849,-0.263711,-0.401980,0.106399,1.572658,3.849170,-1.054036,1.030219,0.344998,...,0.073090,0.014516,-0.080284,1.002952,0.492339,-0.354739,0.060800,0.040539,58.14,0.0
6,TXN104902,-0.337699,1.453236,0.309987,0.033110,0.052142,0.169306,-0.752306,-3.309673,-0.099792,...,2.699560,-2.083815,0.220531,-0.520858,1.031866,0.234530,0.132243,0.133368,5.06,0.0
7,TXN111165,-1.095938,0.680189,1.637330,-1.773343,-0.772781,-1.035813,-0.033875,0.374572,-1.552447,...,-0.041624,-0.361116,-0.105977,0.370015,0.344842,-0.546631,0.147780,0.049541,9.86,0.0
8,TXN162797,1.166816,-0.014960,0.009506,0.132213,-0.454232,-1.294633,0.363236,-0.318797,-0.018520,...,-0.416509,-1.396141,0.161817,0.384353,0.062660,0.616952,-0.115077,0.013413,86.03,0.0
9,TXN124911,-0.492345,0.496637,1.274771,-2.203241,0.369453,-0.827812,1.384719,-0.875227,1.477721,...,0.084593,0.692839,-0.349663,0.078911,0.143761,-0.898951,-0.961124,-0.665970,30.16,0.0
10,TXN161116,-1.095744,-0.159694,2.042509,-0.188011,0.020558,0.691457,2.494615,-2.013099,0.049651,...,-0.723657,0.486901,-0.325267,0.231992,-0.497501,-0.532965,-1.283330,-1.505202,270.50,0.0
11,TXN144259,1.139762,-1.045268,-0.218430,-0.898518,-0.228314,0.794038,-0.737727,0.141667,0.539787,...,-0.196985,-0.861219,-0.164969,-1.808282,0.231302,-0.421824,-0.047513,0.008887,211.90,0.0
12,TXN154071,1.321576,0.410516,-0.010369,0.476203,0.097875,-0.581150,0.138308,-0.203065,-0.027544,...,-0.328378,-0.921823,0.016485,-0.475402,0.355943,0.147948,-0.018806,0.028248,0.00,0.0
13,TXN106686,1.009816,0.063575,0.507703,1.379307,-0.519946,-0.703292,0.132951,-0.101827,-0.009046,...,0.173468,0.393588,-0.081422,0.602593,0.494248,-0.290090,0.025783,0.036902,103.10,0.0
14,TXN144409,1.088427,-0.354380,0.824547,0.341734,-0.781543,0.275222,-0.780542,0.381947,0.539075,...,0.050717,-0.006656,0.037847,-0.324478,0.014613,0.422061,-0.010683,0.008421,42.81,0.0
15,TXN114807,1.112004,-1.010197,-0.118643,-0.369539,-1.049099,-0.603056,-0.291964,-0.074296,-0.504951,...,-0.363709,-0.802129,-0.055957,0.070232,0.247647,1.108655,-0.091838,0.011074,166.38,0.0
16,TXN142130,-0.983675,0.553786,0.483583,-0.058509,-0.344392,0.699729,0.482297,0.690844,-0.060647,...,0.060148,0.039182,0.045533,-0.960565,0.040819,0.423401,0.164000,0.126976,190.50,0.0
17,TXN121969,-3.654141,-1.635087,0.968876,0.590110,-2.072630,0.874875,2.055708,-1.008101,1.850692,...,-0.822269,0.451372,0.076784,0.590307,-0.551186,1.032088,-0.430408,1.307087,644.92,0.0
18,TXN125038,1.139984,-0.317640,1.181312,0.831428,-1.043158,0.131342,-0.811447,0.293875,1.173763,...,-0.081895,-0.085552,0.083728,0.078170,0.116061,0.352118,0.021299,0.018044,16.14,0.0
19,TXN144013,-0.399069,-0.711834,1.690130,-2.045150,-0.929764,-0.430732,0.253493,-0.346093,-2.394331,...,-0.385479,-0.856793,0.203415,-0.198733,-0.174528,-0.493066,-0.093437,-0.111328,155.40,0.0
20,TXN160015,-1.239256,0.944746,1.018545,-0.636940,-0.151227,-0.288815,0.072783,0.501937,0.033875,...,0.058314,0.248851,-0.282309,0.083515,-0.104530,0.484362,-0.030483,0.057828,0.70,0.0
21,TXN171915,-0.239972,1.287683,-0.019043,0.868229,0.119905,-0.544125,0.409713,0.460250,-0.879267,...,0.251752,0.807351,0.117864,0.222037,-0.846284,-0.409833,0.323578,0.154764,4.94,0.0
22,TXN168124,-1.027163,-0.131525,1.878310,-0.821042,0.805153,-0.302903,-0.274316,0.251477,1.035441,...,0.145754,0.416051,-0.014804,-0.303576,-0.401475,0.872745,-0.006290,0.110255,16.80,0.0
23,TXN174067,-0.484529,0.992974,2.876909,2.928093,-0.653781,0.509128,-0.110415,0.313652,-0.745435,...,0.150720,0.509747,-0.283854,0.387394,0.044715,0.398320,0.115046,0.091435,12.06,0.0
24,TXN133385,-1.038176,-0.239640,3.335935,0.960456,-0.712801,1.367258,-0.370713,0.323558,0.764955,...,0.027764,0.712571,-0.265339,0.351354,0.052281,0.729594,-0.143369,-0.127346,101.10,0.0
25,TXN116534,1.366446,-0.046336,0.276028,0.002591,-0.179480,-0.029266,-0.486173,-0.091566,1.881761,...,-0.161560,-0.231286,-0.184278,-0.997412,0.380337,1.121478,-0.093566,-0.009509,19.39,0.0
26,TXN139479,-0.801407,0.167827,2.373830,-0.743503,0.106787,0.660877,0.296686,0.335652,-0.035919,...,0.156298,0.425466,-0.006309,-0.297991,-0.435056,0.259467,-0.105469,-0.129633,62.04,0.0
27,TXN134456,1.121286,0.026712,0.459698,0.719788,-0.294922,-0.098964,-0.081012,0.083191,0.082623,...,-0.062996,0.026904,-0.023517,0.274545,0.458420,0.364816,-0.019427,-0.002338,15.42,0.0
28,TXN149926,1.224408,-0.074501,0.747786,0.131064,-0.631418,-0.307170,-0.544849,-0.019533,1.516594,...,-0.040063,0.115254,-0.064125,0.035981,0.222026,1.032482,-0.093559,-0.008251,19.17,0.0
29,TXN161794,-0.962110,0.989515,1.266002,-1.434295,-0.236607,-0.672836,0.484985,0.029209,1.088457,...,-0.246318,-0.332442,0.024319,0.056669,-0.267371,0.741547,0.333320,0.020642,6.37,0.0
30,TXN133095,-0.570878,0.783759,0.664154,-2.400704,0.541043,-0.728359,0.987068,-0.190923,0.925170,...,0.023456,0.437297,-0.389781,-0.507332,0.184242,-0.798039,0.336099,0.027357,0.00,0.0
31,TXN120550,-3.581693,-1.400701,-0.819254,-2.218626,-1.639143,0.245352,1.269567,-0.686796,-1.939064,...,-0.863134,-0.818750,-1.610582,-0.157313,-0.728488,-0.782187,-0.683970,-1.107068,551.10,0.0
32,TXN179868,-0.383545,1.670879,0.195795,2.870871,0.416127,-0.152754,0.457216,0.272831,-1.524174,...,-0.016573,0.026514,-0.072964,-0.111619,-0.372821,0.131766,-0.097984,-0.160144,17.26,0.0
33,TXN105846,-0.976220,0.296722,0.724557,-1.877115,-0.217514,-0.421514,0.006150,0.427438,-1.813636,...,-0.444240,-1.060138,0.052283,-0.499131,-0.316535,0.682065,0.145836,0.066014,53.60,0.0
34,TXN108187,1.219500,0.302076,0.269542,0.656323,-0.183834,-0.586947,0.018420,-0.056976,0.049682,...,-0.242843,-0.716187,0.156911,0.030255,0.138682,0.129914,-0.012894,0.030526,2.77,0.0
35,TXN181366,1.291673,0.830819,-0.643113,1.140083,0.611385,-0.749203,0.408710,-0.265128,-0.269927,...,-0.106846,-0.136265,-0.242851,-0.563411,0.855373,-0.277224,0.039147,0.053127,1.61,0.0
36,TXN128845,-0.276983,0.864090,1.147364,0.086387,0.598889,0.354125,0.929263,-0.149389,-0.424849,...,-0.071367,-0.110378,-0.319938,-0.861136,0.157018,-0.485473,-0.240168,-0.221258,53.27,0.0
37,TXN160392,0.952823,-0.736034,1.123715,0.184722,-1.205207,0.311624,-0.769279,0.341891,1.031103,...,-0.100823,-0.243182,0.061593,0.283677,-0.042555,0.935298,-0.041509,0.015031,107.89,0.0
38,TXN178979,1.290252,0.254854,0.312090,0.468020,-0.202509,-0.719724,0.071742,-0.182206,0.029946,...,-0.278389,-0.817306,0.070544,-0.106848,0.290940,0.122310,-0.027089,0.013009,0.22,0.0
39,TXN174518,-0.818049,-0.390409,0.786516,-1.882437,-0.004257,0.566302,0.086392,-0.276219,0.051324,...,0.187672,0.881285,-0.278389,-0.889572,-0.750296,-0.516505,-0.590424,0.161379,93.96,0.0
40,TXN103376,-0.002635,0.027779,-0.349417,-1.988229,1.964357,3.322313,-0.302342,0.770368,-1.716467,...,-0.311813,-0.548158,-0.050693,1.041553,-0.511130,1.049166,0.100434,0.143784,9.11,0.0
41,TXN163672,1.219023,0.268346,0.257551,0.648451,-0.231099,-0.623997,-0.034086,-0.021849,0.121969,...,-0.277070,-0.758264,0.167983,0.012554,0.117944,0.127987,-0.009621,0.030855,1.70,0.0
42,TXN132613,1.412473,-1.321356,0.430121,-1.402639,-1.718254,-0.432151,-1.309752,0.209140,-1.590541,...,-0.159068,-0.253264,0.113503,0.113092,0.122565,-0.197172,0.012235,-0.000250,33.28,0.0
43,TXN130656,-1.388775,1.352666,0.681922,1.340197,-0.613739,0.311812,0.252467,-0.244875,-0.040657,...,0.682168,-0.108187,0.087370,0.061773,-0.012074,-0.203982,0.535760,0.158627,125.95,0.0
44,TXN164649,1.225070,-0.582491,-0.099820,-0.518757,-0.705295,-0.552290,-0.444200,-0.066614,-0.913362,...,-0.001979,-0.180599,-0.133971,-0.065167,0.464335,-0.305129,0.007138,0.042760,119.49,0.0
45,TXN138890,-1.545232,0.035908,1.294970,1.011716,-0.192091,0.174300,0.497132,-0.000866,0.064580,...,0.016157,0.467590,-0.061171,0.016974,-0.217689,-0.355064,0.072162,0.475761,206.86,0.0
46,TXN100052,-2.374345,0.295307,1.217605,1.048197,1.926648,-1.117485,0.762777,0.073112,-1.619154,...,0.069662,-0.015478,-0.797181,0.145189,0.726686,-0.192773,-0.268802,-0.537763,9.42,0.0
47,TXN148145,0.868306,-0.655373,1.016168,1.339466,-0.849776,0.843383,-0.733524,0.475857,0.857378,...,0.064989,0.044742,-0.119575,-0.343079,0.252644,-0.350333,0.051661,0.040756,164.80,0.0
48,TXN181865,0.985088,-0.334397,-0.076555,1.293823,-0.125431,0.572854,-0.304652,0.241494,0.772013,...,-0.061898,-0.213374,-0.385384,-0.899699,0.724297,-0.232239,0.038521,0.049465,175.00,0.0
49,TXN166737,1.244718,0.309514,0.304189,0.710050,-0.384438,-1.092009,0.071239,-0.190914,0.084734,...,-0.294081,-0.858010,0.137275,0.333751,0.208960,0.094318,-0.024425,0.029952,6.54,0.0

In [66]:
df.shape

(61835, 31)

In [8]:
df.columns

Index(['Txn_ID', 'Feature_1', 'Feature_2', 'Feature_3', 'Feature_4',
       'Feature_5', 'Feature_6', 'Feature_7', 'Feature_8', 'Feature_9',
       'Feature_10', 'Feature_11', 'Feature_12', 'Feature_13', 'Feature_14',
       'Feature_15', 'Feature_16', 'Feature_17', 'Feature_18', 'Feature_19',
       'Feature_20', 'Feature_21', 'Feature_22', 'Feature_23', 'Feature_24',
       'Feature_25', 'Feature_26', 'Feature_27', 'Feature_28', 'Txn_Value',
       'Risk_Flag'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61835 entries, 0 to 61834
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Txn_ID      61835 non-null  object
 1   Feature_1   61835 non-null  float64
 2   Feature_2   61835 non-null  float64
 3   Feature_3   61835 non-null  float64
 4   Feature_4   61835 non-null  float64
 5   Feature_5   61835 non-null  float64
 6   Feature_6   61835 non-null  float64
 7   Feature_7   61835 non-null  float64
 8   Feature_8   61835 non-null  float64
 9   Feature_9   61835 non-null  float64
 10  Feature_10  61835 non-null  float64
 11  Feature_11  61835 non-null  float64
 12  Feature_12  61835 non-null  float64
 13  Feature_13  61835 non-null  float64
 14  Feature_14  61835 non-null  float64
 15  Feature_15  61835 non-null  float64
 16  Feature_16  61835 non-null  float64
 17  Feature_17  61835 non-null  float64
 18  Feature_18  61835 non-null  float64
 19  Feature_19  61835 non-null  float64
 20  Feature_20  61835 non-null  float64
 21  Feature_21  61835 non-null  float64
 22  Feature_22  61835 non-null  float64
 23  Feature_23  61835 non-null  float64
 24  Feature_24  61835 non-null  float64
 25  Feature_25  61835 non-null  float64
 26  Feature_26  61835 non-null  float64
 27  Feature_27  61835 non-null  float64
 28  Feature_28  61835 non-null  float64
 29  Txn_Value   61835 non-null  float64
 30  Risk_Flag   61835 non-null  float64
dtypes: float64(30), object(1)
memory usage: 14.6+ MB

In [10]:
df.nunique()

Txn_ID        61835
Feature_1     61835
Feature_2     61835
Feature_3     61835
Feature_4     61835
Feature_5     61835
Feature_6     61835
Feature_7     61835
Feature_8     61835
Feature_9     61835
Feature_10    61835
Feature_11    61835
Feature_12    61835
Feature_13    61835
Feature_14    61835
Feature_15    61835
Feature_16    61835
Feature_17    61835
Feature_18    61835
Feature_19    61835
Feature_20    61835
Feature_21    61835
Feature_22    61835
Feature_23    61835
Feature_24    61835
Feature_25    61835
Feature_26    61835
Feature_27    61835
Feature_28    61835
Txn_Value     19838
Risk_Flag         2
dtype: int64

# chechk missing

In [117]:
missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing %": (df.isnull().sum() / len(df) * 100).round(2)
})

missing = missing[missing["Missing Count"] > 0]
missing = missing.sort_values("Missing %", ascending=False)

missing

Empty DataFrame
Columns: [Missing Count, Missing %]
Index: []

 > No missing value exists

# Drop ID column

> No need of Trx_Id

In [118]:
df.drop(columns=["Txn_ID"],inplace = True)

# Seperate Feature and target columns

In [119]:
X = df.drop("Risk_Flag", axis=1)
y = df["Risk_Flag"]

# check class imbalance

> See most of the data are Risk flag 0 . That indicates         highly  imbalanced target datasets

In [120]:
print(df["Risk_Flag"].value_counts())

print(df["Risk_Flag"].value_counts(normalize=True) * 100)

Risk_Flag
0.0    61708
1.0      127
Name: count, dtype: int64
Risk_Flag
0.0    99.794615
1.0     0.205385
Name: proportion, dtype: float64

# Startified Split

 > What is a stratified split?

A stratified split ensures that the class distribution (the proportion of each class) remains approximately the same in both the training and validation/test sets.

In [121]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Train a Baseline Model

## Random Forest Classifier

In [122]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

# Make prediction

In [123]:
y_pred = rf.predict(X_valid)

y_prob = rf.predict_proba(X_valid)[:,1]

# Evaluate

In [124]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

print("Accuracy :", accuracy_score(y_valid, y_pred))
print("Precision:", precision_score(y_valid, y_pred))
print("Recall   :", recall_score(y_valid, y_pred))
print("F1 Score :", f1_score(y_valid, y_pred))
print("ROC AUC  :", roc_auc_score(y_valid, y_prob))

print(confusion_matrix(y_valid, y_pred))

print(classification_report(y_valid, y_pred))

Accuracy : 0.9991913964583164
Precision: 0.8947368421052632
Recall   : 0.68
F1 Score : 0.7727272727272727
ROC AUC  : 0.9592383730351645
[[12340     2]
 [    8    17]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     12342
         1.0       0.89      0.68      0.77        25

    accuracy                           1.00     12367
   macro avg       0.95      0.84      0.89     12367
weighted avg       1.00      1.00      1.00     12367

 > Here Type 2 error is most expensive . So, higher recall score needed

 > Good baseline. Now let's see if XGBoost or LightGBM can improve recall without sacrificing too much precision.

# XGBoost for better Recall Score

In [125]:
from xgboost import XGBClassifier

## Calculate scale_pos_weight

In [126]:
negative = y_train.value_counts()[0]
positive = y_train.value_counts()[1]

scale_pos_weight = negative / positive

print(scale_pos_weight)

483.98039215686276

 > This tells XGBoost that the positive class (fraud) is much rarer and should receive more emphasis during training.

# Train XGBoost

In [127]:
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    scale_pos_weight=scale_pos_weight
)

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

# Predict

In [23]:
y_pred = xgb.predict(X_valid)

y_prob = xgb.predict_proba(X_valid)[:, 1]

# Evaluate

In [128]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

print("Accuracy :", accuracy_score(y_valid, y_pred))
print("Precision:", precision_score(y_valid, y_pred))
print("Recall   :", recall_score(y_valid, y_pred))
print("F1 Score :", f1_score(y_valid, y_pred))
print("ROC AUC  :", roc_auc_score(y_valid, y_prob))

print(confusion_matrix(y_valid, y_pred))
print(classification_report(y_valid, y_pred))

Accuracy : 0.9991913964583164
Precision: 0.8947368421052632
Recall   : 0.68
F1 Score : 0.7727272727272727
ROC AUC  : 0.9592383730351645
[[12340     2]
 [    8    17]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     12342
         1.0       0.89      0.68      0.77        25

    accuracy                           1.00     12367
   macro avg       0.95      0.84      0.89     12367
weighted avg       1.00      1.00      1.00     12367

# Hyper parameter tuning

In [26]:
from sklearn.model_selection import RandomizedSearchCV

In [27]:
param_grid = {
    "n_estimators": [200, 300, 500],
    "max_depth": [3, 4, 5, 6],
    "learning_rate": [0.01, 0.03, 0.05, 0.1],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0]
}

In [28]:
search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_grid,
    n_iter=20,
    scoring="roc_auc",
    cv=5,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

In [29]:
search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=0.8, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=True,
                                           eval_metric='logloss',
                                           feature_types=None,
                                           feature_weights=None, gamma=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_constr...
                                           min_child_weight=None, missing=nan,
                                           monotone_constraints=None,
                                           multi_strategy=None,
                                           n_estimators=300, n_jobs=None,
                                           num_parallel_tree=None, ...),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'colsample_bytree': [0.7, 0.8, 1.0],
                                        'learning_rate': [0.01, 0.03, 0.05,
                                                          0.1],
                                        'max_depth': [3, 4, 5, 6],
                                        'n_estimators': [200, 300, 500],
                                        'subsample': [0.7, 0.8, 1.0]},
                   random_state=42, scoring='roc_auc', verbose=1)

## see the best parameters

In [30]:
print(search.best_params_)

{'subsample': 0.7, 'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

# Create the best model

In [31]:
best_xgb = XGBClassifier(
    subsample=0.7,
    n_estimators=200,
    max_depth=3,
    learning_rate=0.03,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    scale_pos_weight=scale_pos_weight
)

## Train best model

In [32]:
best_xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

## Predict from model

In [33]:
y_pred = best_xgb.predict(X_valid)

y_prob = best_xgb.predict_proba(X_valid)[:,1]

## Evaluate

In [34]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

print("Accuracy :", accuracy_score(y_valid, y_pred))
print("Precision:", precision_score(y_valid, y_pred))
print("Recall   :", recall_score(y_valid, y_pred))
print("F1 Score :", f1_score(y_valid, y_pred))
print("ROC AUC  :", roc_auc_score(y_valid, y_prob))

print(confusion_matrix(y_valid, y_pred))
print(classification_report(y_valid, y_pred))

Accuracy : 0.9976550497291178
Precision: 0.45454545454545453
Recall   : 0.8
F1 Score : 0.5797101449275363
ROC AUC  : 0.9559812023983146
[[12318    24]
 [    5    20]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     12342
         1.0       0.45      0.80      0.58        25

    accuracy                           1.00     12367
   macro avg       0.73      0.90      0.79     12367
weighted avg       1.00      1.00      1.00     12367

> Here tuned model became more aggressive so that precision , F1 Score are extremely low

# Over all Decision

 > Instead of tuned model , our baseline model performs well all across

 > Instead of changing the model,   change the decision threshold.

# Baseline model with threshold

In [37]:
y_prob = xgb.predict_proba(X_valid)[:, 1]

In [38]:


thresholds = [0.50, 0.45, 0.40, 0.35, 0.30, 0.25]

for t in thresholds:
    y_pred = (y_prob >= t).astype(int)

    print(f"Threshold: {t}")
    print("Precision:", round(precision_score(y_valid, y_pred), 3))
    print("Recall   :", round(recall_score(y_valid, y_pred), 3))
    print("F1 Score :", round(f1_score(y_valid, y_pred), 3))
    print("-"*40)

Threshold: 0.5
Precision: 0.905
Recall   : 0.76
F1 Score : 0.826
----------------------------------------
Threshold: 0.45
Precision: 0.905
Recall   : 0.76
F1 Score : 0.826
----------------------------------------
Threshold: 0.4
Precision: 0.905
Recall   : 0.76
F1 Score : 0.826
----------------------------------------
Threshold: 0.35
Precision: 0.905
Recall   : 0.76
F1 Score : 0.826
----------------------------------------
Threshold: 0.3
Precision: 0.905
Recall   : 0.76
F1 Score : 0.826
----------------------------------------
Threshold: 0.25
Precision: 0.905
Recall   : 0.76
F1 Score : 0.826
----------------------------------------

# Decision

 > Nothing has improve after selecting the threshold , So best model is Baseline model

# Try LightGBM

In [39]:
from lightgbm import LGBMClassifier

# Calculate the class imbalance
negative = y_train.value_counts()[0]
positive = y_train.value_counts()[1]

scale_pos_weight = negative / positive


#Build the model

lgbm = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=-1,          # No depth limit
    num_leaves=31,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    random_state=42
)

## Train

In [40]:
lgbm.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 102, number of negative: 49366
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.056277 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7395
[LightGBM] [Info] Number of data points in the train set: 49468, number of used features: 29
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.002062 -> initscore=-6.182044
[LightGBM] [Info] Start training from score -6.182044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(colsample_bytree=0.8, learning_rate=0.05, n_estimators=300,
               random_state=42, scale_pos_weight=np.float64(483.98039215686276),
               subsample=0.8)

# Predict

In [41]:
y_pred = lgbm.predict(X_valid)

y_prob = lgbm.predict_proba(X_valid)[:,1]

# Evaluate

In [42]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

print("Accuracy :", accuracy_score(y_valid, y_pred))
print("Precision:", precision_score(y_valid, y_pred))
print("Recall   :", recall_score(y_valid, y_pred))
print("F1 Score :", f1_score(y_valid, y_pred))
print("ROC AUC  :", roc_auc_score(y_valid, y_prob))

print(confusion_matrix(y_valid, y_pred))
print(classification_report(y_valid, y_pred))

Accuracy : 0.9179267405191235
Precision: 0.020348837209302327
Recall   : 0.84
F1 Score : 0.039735099337748346
ROC AUC  : 0.8790325717063684
[[11331  1011]
 [    4    21]]
              precision    recall  f1-score   support

         0.0       1.00      0.92      0.96     12342
         1.0       0.02      0.84      0.04        25

    accuracy                           0.92     12367
   macro avg       0.51      0.88      0.50     12367
weighted avg       1.00      0.92      0.96     12367

# Model Comparasion

In [43]:
comparison = pd.DataFrame({
    "Model": ["Random Forest", "XGBoost", "Tuned XGBoost", "LightGBM"],
    "Accuracy": [0.999191, 0.999353, 0.997655, 0.917927],
    "Precision": [0.8947, 0.9048, 0.4545, 0.0203],
    "Recall": [0.68, 0.76, 0.80, 0.84],
    "F1 Score": [0.7727, 0.8261, 0.5797, 0.0397],
    "ROC-AUC": [0.9592, 0.9779, 0.9560, 0.8790]
})

comparison = comparison.sort_values("ROC-AUC", ascending=False)

comparison

           Model  Accuracy  Precision  Recall  F1 Score  ROC-AUC
1        XGBoost  0.999353     0.9048    0.76    0.8261   0.9779
0  Random Forest  0.999191     0.8947    0.68    0.7727   0.9592
2  Tuned XGBoost  0.997655     0.4545    0.80    0.5797   0.9560
3       LightGBM  0.917927     0.0203    0.84    0.0397   0.8790

# Decision

 > It gives Low FP But gives highest TN . So this is also worst . We will still look after the baseline XGBoost Classifier

# Final Decision

 > XGBoost is the winner

# Retrain on the entire training dataset

In [129]:
X = df.drop(columns=["Risk_Flag"])
y = df["Risk_Flag"]


negative = y.value_counts()[0]
positive = y.value_counts()[1]

scale_pos_weight = negative / positive

final_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    scale_pos_weight=200
)

final_model.fit(X, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [134]:
probs = final_model.predict_proba(X_test)[:,1]    # ✅ CORRECT

In [135]:
predictions = (probs >= 0.5).astype(int)

import pandas as pd
print(pd.Series(predictions).value_counts())

0    20575
1       37
Name: count, dtype: int64

In [136]:
predictions = (probs >= 0.5).astype(int)

In [137]:
import pandas as pd

print(pd.Series(predictions).value_counts())
print(len(predictions))

0    20575
1       37
Name: count, dtype: int64
20612

# Load the test datasets

In [138]:
test = pd.read_csv("/content/sample_data/finnova_test.csv")
test.head(10)

,Txn_ID,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,...,Feature_20,Feature_21,Feature_22,Feature_23,Feature_24,Feature_25,Feature_26,Feature_27,Feature_28,Txn_Value
0,TXN178145,-2.678101,1.559655,0.755455,-1.021001,0.035179,0.738524,-4.615351,-7.743908,1.168926,...,-0.950498,4.158070,-1.438561,-1.251894,0.040011,-1.931469,0.626741,0.554614,0.347282,67.41
1,TXN173470,-0.759192,1.191944,1.061377,-0.182587,-0.206468,-0.448454,0.202149,0.560893,-0.696283,...,-0.039225,-0.157202,-0.609292,-0.015482,-0.046662,-0.182014,0.080049,0.134530,0.039254,4.68
2,TXN140553,-0.512311,0.909588,1.350344,-0.123350,0.300001,-0.619883,0.765362,-0.085070,-0.482044,...,0.249208,-0.226422,-0.630091,-0.004571,-0.118709,-0.082035,0.104127,0.252798,0.121758,33.23
3,TXN175362,-0.458975,-0.352457,1.571497,-2.734177,-0.688841,-0.318401,-0.226532,0.132952,-2.496436,...,-0.412563,-0.186643,-0.352948,-0.327082,-0.433474,0.419902,-0.250521,0.016607,0.037794,18.68
4,TXN169993,-0.387071,-3.477373,-0.963639,0.312471,-1.891890,-0.751104,1.009930,-0.522413,-0.828331,...,1.383087,0.122351,-1.219617,-0.828006,0.470041,0.078050,0.996502,-0.250285,0.161566,1224.96
5,TXN134722,-0.748376,0.533281,2.037012,-0.245712,-0.033991,-0.852538,0.943533,-0.316797,0.218093,...,-0.107716,-0.200967,-0.427199,-0.029808,0.714951,-0.255026,-0.082449,-0.228289,-0.068897,55.28
6,TXN102647,-0.854196,1.302546,1.671521,2.606728,-0.285337,0.965976,-0.414007,0.949676,-1.345244,...,0.089609,0.275696,0.736005,-0.149210,-0.321610,-0.299339,0.370545,0.276742,0.112387,11.55
7,TXN112339,1.157101,-1.524608,0.298536,-1.341093,-1.528873,-0.349021,-0.860541,-0.015236,-2.160616,...,-0.077395,-0.028061,-0.050087,-0.059709,0.219030,0.219252,-0.216801,0.009262,0.029026,207.06
8,TXN159443,0.820115,-0.625490,-0.615280,0.039454,-0.016426,-0.341025,0.563990,-0.164680,-0.448554,...,0.406577,0.156386,-0.057410,-0.313512,-0.200986,0.411597,1.080975,-0.142075,0.010315,307.84
9,TXN119639,-1.517607,0.265210,1.270074,-1.259095,0.359396,-1.009487,0.562472,-0.115231,0.266252,...,-0.073158,-0.228744,-0.190575,0.404848,-0.071187,-0.072642,0.773654,0.386367,0.162777,20.31

# Save the ID column

In [106]:
txn_id = test["Txn_ID"]

# Prepare test features

In [107]:
X_test = test.drop(columns=["Txn_ID"])

# Predict

 > This depends on what the competition requires.

If it wants class labels

In [108]:
predictions = final_model.predict(X_test)

# Submission

In [139]:
submission = pd.DataFrame({
    "Txn_ID": test["Txn_ID"],
    "Risk_Flag": predictions
})

In [140]:
print(submission.shape)
submission.head()

(20612, 2)

      Txn_ID  Risk_Flag
0  TXN178145          0
1  TXN173470          0
2  TXN140553          0
3  TXN175362          0
4  TXN169993          0

In [141]:
submission.to_csv("submission.csv", index=False)

In [142]:
submission.head(10)

      Txn_ID  Risk_Flag
0  TXN178145          0
1  TXN173470          0
2  TXN140553          0
3  TXN175362          0
4  TXN169993          0
5  TXN134722          0
6  TXN102647          0
7  TXN112339          0
8  TXN159443          0
9  TXN119639          0

In [113]:
submission["Risk_Flag"].value_counts()

Risk_Flag
0    20575
1       37
Name: count, dtype: int64

# Download the file (Google Colab)

In [143]:
from google.colab import files

files.download("submission.csv")